### ISSUE TITLE
Factory created records are not done through transactions in specs

### ISSUE THREAD

**Issue by crimson-knight** [imdrasil/factory#9]
I'm using Factory and Jennifer in my test suite. 

I have this code from the Jennifer docs that recommend using transactions to keep from running db cleaning after every spec:
```crystal
Spec.before_each do
  Jennifer::Adapter.default_adapter.begin_transaction
end

Spec.after_each do
  Jennifer::Adapter.default_adapter.rollback_transaction
end
```

This works fine for anything I create inside of the tests, however now that I'm using Factory, the records created by Factory are not being cleaned.

Is there another way I can configure this to work?

**Comment by imdrasil** [comment]
Hi, could share an example of your setup?

**Comment by crimson-knight** [comment]
Okay I was mistaken, it's working as expected. I had my factories outside of the correct block and then it wasn't rolling back but those aren't in the transaction so that's why it wasn't removing them.
